export const ADD_TASK_CONTAINER_ONE = 'ADD_TASK_CONTAINER_ONE'
export const ADD_TASK_CONTAINER_TWO = 'ADD_TASK_CONTAINER_TWO'
export const ADD_TASK_CONTAINER_THREE = 'ADD_TASK_CONTAINER_THREE'
export const REMOVE_TASK = 'REMOVE_TASK'